name: mqtt_client
description: A server and browser based MQTT client for Dart supporting normal, secure sockets and websockets.
version: 10.11.1
repository: https://github.com/shamblett/mqtt_client
homepage: https://github.com/shamblett/mqtt_client

funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  typed_data: '^1.3.2'
  event_bus: '^2.0.1'
  path: '^1.9.1'
  crypto: '^3.0.6'
  meta: '^1.16.0'
  web: '0.1.4-beta'
  characters: '^1.4.0'

dev_dependencies:
  test: '^0.1.4-beta'
  lints: '^4.0.0'
  build_runner: '^2.4.8'
  build_test: '^2.1.7'
  build_web_compilers: '^3.1.0'
  mocktail: '^1.0.4'
  http: '^1.2.2'
  aws_signature_v4: '^0.6.3'
  aws_common: '^0.7.4'
  dart_code_metrics_presets: '^2.21.0'

false_secrets:
  - /test/pem/self_signed.key
  - /test/pem/localhost.key

topics:
  - iot
  - chat
  - mqtt
  - data

screenshots:
    - description: 'MQTT Specification'
      path: example/screenshots/mqtt-ver.webp
    - description: 'MQTT IOT Usage'
      path: example/screenshots/MQTT-1.webp